### ISSUE TITLE
Maven Local Repositories?

### ISSUE THREAD

**Issue by thebradbain** [Rajawali/RajawaliVR#17]
I'm a bit inexperienced with Maven/Gradle. Do I run `./RajawaliVR/RajawaliVR/gradlew clean assembleRelease uploadArchives` from anywhere special? Because running the task (or even `./RajawaliVR/RajawaliVR/gradlew tasks`) gives the error code: 

> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

Thanks for your help.

**Comment by RamIndani** [comment]
Is this the issue with library ? I guess not! posting questions or help on www.stackoverflow.com can be good. I am not author of this library but I do love this library so just suggestion.

**Comment by drbago** [comment]
This is not an issue with RajawaliVR.  Your question is a common question for getting started with Android SDK and Gradle.  Take @RamIndani's advice and search that issue on stackoverflow.com or google.com.

**Comment by Eldho93** [comment]
@RamIndani : Its  a genuine doubt. The library docs could have been made a little more simpler so that it is understandable to beginners .Have been searching an answer for this  since hours.

**Comment by JCFerrerG** [comment]
This is definitely not an issue with the library.

The reason you are getting an "SDK location not found" error is because the gradle plugin for Android depends the Android SDK (see [this page](http://developer.android.com/tools/building/plugin-for-gradle.html) for documentation).  Many command-line interface (CLI) tools for Android expect the ANDROID_HOME environment variable to point to the location of an installed SDK.

This is not an _issue_ with this library; it is a general Android development question.  GitHub issues are not appropriate for this type of support question.  First, search google.com and stackoverflow.com for answers to your questions.  If you cannot reasonably find an answer via search, appropriate places to ask these types of questions are in beginner Android sections in chat rooms, mailing lists, and StackOverflow.

Finally, it is worth noting that [this repository is no longer actively maintained](https://github.com/Rajawali/RajawaliVR/commit/64c895cff13d260049a301b9edc0119ba804dca7), as RajawaliVR has been moved into the [main Rajawali repo](https://github.com/Rajawali/Rajawali).

I recommend this issue be marked as closed.

**Comment by thebradbain** [comment]
Thank you all for your passionate input! 

I realized soon after I posted 9 months ago that this was, indeed, a general android support question. I thought I had closed the issue, so thank you for bringing it to my attention that I had not.

Carry on and have a great day!
